FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
	sudo \
	wget \
	vim
WORKDIR /opt
RUN wget https://repo.continuum.io/archive/Anaconda3-2022.10-Linux-aarch64.sh && \
	sh Anaconda3-2022.10-Linux-aarch64.sh -b -p /opt/anaconda3 && \
	rm -f Anaconda3-2022.10-Linux-aarch64.sh

ENV PATH /opt/anaconda3/bin:$PATH

RUN pip install --upgrade pip
WORKDIR /
CMD ["jupyter","lab","--ip=0.0.0.0","--allow-root","--LabApp.token=''"]